# Generated by Django 4.0.1 on 2022-01-20 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='about',
            field=models.TextField(default='文章简介'),
            preserve_default=False,
        ),
    ]
