# Generated by Django 4.0.1 on 2022-01-20 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='summary',
            field=models.TextField(default='活动预览'),
            preserve_default=False,
        ),
    ]
